# Generated by Django 2.0.7 on 2018-07-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nicname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='realname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userroles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
